CFLAGS=-O4

all: day10a day11a day11b day12a-example day12a day12b day13a-ll day13a day13b day3a day3b day6a day6b day9a day9b 

clean:
	rm day10a day11a day11b day12a-example day12a day12b day13a-ll day13a day13b day3a day3b day6a day6b day9a day9b 
